### ISSUE TITLE
Paper descriptions

### ISSUE THREAD

**Issue by tskarvone** [probabilistic-numerics/website#4]
Is it possible to reinstate descriptions for some of the papers in the literature section that the old version of the website had?

**Comment by JonathanWenger** [comment]
Descriptions are visible under "ABS" for each paper from 790005442e1d7b50caa6e068784fd26a1ed4ce40 onwards.


![Screenshot from 2021-09-27 17-15-32](https://user-images.githubusercontent.com/29815984/134936882-19616506-88b3-4024-89e6-61b14e2b6da6.png)
